const DATA_KEY = "adhi03f24_v3";

const DEFAULT_DATA = {
  profile: {
    name: "Adhithiyan Maliackal",
    username: "adhi03f24",
    dob: "2003-02-24",
    title: "AI-Augmented Senior Software Developer",
    subtitle: "Ethical Hacker → Vibe Coder → AI Sensei",
    tagline: "I don't just write code — I breathe it.",
    bio: "Born 24 Feb 2003. Ethical Hacker since 2021. Evolved into an AI-Augmented Senior Software Developer and Vibe Coder. Now training the next generation in Prompt Engineering, AI-Augmented Development & Cybersecurity. 100+ certifications. The shadows remember.",
    email: "adhithiyanmaliackal@gmail.com",
    phone: "+91 7559964383",
    location: "India",
    social: {
      github: "https://github.com/adhi03f24",
      linkedin: "https://linkedin.com/in/adhi03f24",
      twitter: "https://twitter.com/adhi03f24",
      instagram: "https://instagram.com/adhi03f24",
      youtube: "https://youtube.com/@adhi03f24"
    },
    resumeLink: ""
  },
  stats: {
    level: 42, xp: "142,800", rank: "S", class: "SHADOW MONARCH",
    certsCount: 100, yearsActive: 4
  },
  timeline: [
    { id:1, year:"2021", phase:"ARC 1", title:"THE HACKER AWAKENS", desc:"Entered the digital underworld. Mastered penetration testing, vulnerability assessment, network exploitation. Earned certifications from Google, Microsoft, IBM, Cisco, EC-Council. The shadows became a training ground.", icon:"fa-skull-crossbones", color:"#00ff41" },
    { id:2, year:"2022", phase:"ARC 2", title:"THE TRANSFORMATION", desc:"Realized the power of building over breaking. Transitioned from hacking systems to engineering them. Mastered full-stack development — React, Node.js, Python, TypeScript, MEAN stack. The hacker's eye became a developer's instinct.", icon:"fa-bolt-lightning", color:"#a855f7" },
    { id:3, year:"2023", phase:"ARC 3", title:"AI AUGMENTATION", desc:"Evolved into an AI-Augmented Vibe Coder. Prompt engineering, LLMs, GitHub Copilot, LangChain. Let AI amplify every keystroke. The fusion of security knowledge and AI created something unprecedented.", icon:"fa-brain", color:"#ff1744" },
    { id:4, year:"2024-NOW", phase:"ARC 4", title:"THE SENSEI", desc:"The dojo is open. Training students in Prompt Engineering, AI-Augmented Development & Cybersecurity. 100+ certifications earned. The legacy begins — forging the next generation.", icon:"fa-torii-gate", color:"#ffd700" }
  ],
  skills: [
    { id:1,name:"Python",level:95,cat:"language",rank:"S" },
    { id:2,name:"JavaScript",level:92,cat:"language",rank:"S" },
    { id:3,name:"TypeScript",level:88,cat:"language",rank:"A" },
    { id:4,name:"HTML/CSS",level:93,cat:"language",rank:"S" },
    { id:5,name:"Rust",level:65,cat:"language",rank:"B" },
    { id:6,name:"C/C++",level:70,cat:"language",rank:"B" },
    { id:7,name:"SQL",level:80,cat:"language",rank:"A" },
    { id:8,name:"Bash/Shell",level:92,cat:"language",rank:"S" },
    { id:9,name:"React/Next.js",level:90,cat:"framework",rank:"S" },
    { id:10,name:"Node.js/Express",level:88,cat:"framework",rank:"A" },
    { id:11,name:"Django/Flask",level:85,cat:"framework",rank:"A" },
    { id:12,name:"FastAPI",level:82,cat:"framework",rank:"A" },
    { id:13,name:"MEAN Stack",level:85,cat:"framework",rank:"A" },
    { id:14,name:"Selenium",level:80,cat:"framework",rank:"A" },
    { id:15,name:"Prompt Engineering",level:97,cat:"ai",rank:"S+" },
    { id:16,name:"LangChain/LLMs",level:94,cat:"ai",rank:"S" },
    { id:17,name:"OpenAI/GPT",level:95,cat:"ai",rank:"S" },
    { id:18,name:"GitHub Copilot",level:93,cat:"ai",rank:"S" },
    { id:19,name:"TensorFlow",level:80,cat:"ai",rank:"A" },
    { id:20,name:"AI-Augmented Dev",level:96,cat:"ai",rank:"S+" },
    { id:21,name:"Penetration Testing",level:95,cat:"security",rank:"S" },
    { id:22,name:"Network Security",level:92,cat:"security",rank:"S" },
    { id:23,name:"Kali Linux",level:93,cat:"security",rank:"S" },
    { id:24,name:"Metasploit",level:90,cat:"security",rank:"S" },
    { id:25,name:"Burp Suite",level:88,cat:"security",rank:"A" },
    { id:26,name:"OWASP ZAP",level:85,cat:"security",rank:"A" },
    { id:27,name:"Nmap",level:90,cat:"security",rank:"S" },
    { id:28,name:"Wireshark",level:88,cat:"security",rank:"A" },
    { id:29,name:"OSINT",level:85,cat:"security",rank:"A" },
    { id:30,name:"Red Teaming LLMs",level:88,cat:"security",rank:"A" },
    { id:31,name:"Reverse Engineering",level:78,cat:"security",rank:"A" },
    { id:32,name:"Privilege Escalation",level:85,cat:"security",rank:"A" },
    { id:33,name:"SOC Operations",level:82,cat:"security",rank:"A" },
    { id:34,name:"Docker/K8s",level:82,cat:"tool",rank:"A" },
    { id:35,name:"Git/CI-CD",level:90,cat:"tool",rank:"S" },
    { id:36,name:"Linux Admin",level:93,cat:"tool",rank:"S" },
    { id:37,name:"AWS/Azure/GCP",level:82,cat:"tool",rank:"A" },
    { id:38,name:"Postman/API",level:85,cat:"tool",rank:"A" }
  ],
  certifications: [
    {id:1,t:"Google Cybersecurity Professional Certificate",p:"Google",c:8,cat:"pro"},
    {id:2,t:"Microsoft Cybersecurity Analyst Professional Certificate",p:"Microsoft",c:9,cat:"pro"},
    {id:3,t:"Certified Ethical Hacker (CEH) v.12",p:"EC-Council / Packt",c:3,cat:"pro"},
    {id:4,t:"CompTIA PenTest+ (PT0-002)",p:"Packt",c:3,cat:"pro"},
    {id:5,t:"Cisco CCNP Security SCOR (350-701)",p:"Cisco / Packt",c:3,cat:"pro"},
    {id:6,t:"Cisco CCNP Enterprise ENCOR (350-401)",p:"Cisco / Packt",c:3,cat:"pro"},
    {id:7,t:"CompTIA A+ Core 1 (220-1101)",p:"Packt",c:3,cat:"pro"},
    {id:8,t:"Cybersecurity Operations Fundamentals",p:"Cisco",c:7,cat:"pro"},
    {id:9,t:"Microsoft Azure Security Tools",p:"Microsoft",c:5,cat:"pro"},
    {id:10,t:"Certified Cloud Security Professional (CCSP)",p:"Infosec",c:1,cat:"pro"},
    {id:11,t:"Advanced Network Security",p:"LearnQuest",c:3,cat:"spec"},
    {id:12,t:"Managing Cybersecurity",p:"Kennesaw State University",c:5,cat:"spec"},
    {id:13,t:"Information Assurance Analysis",p:"Johns Hopkins University",c:3,cat:"spec"},
    {id:14,t:"Introduction to Cyber Security",p:"New York University",c:4,cat:"spec"},
    {id:15,t:"Cybersecurity Fundamentals",p:"IBM",c:4,cat:"spec"},
    {id:16,t:"The Complete Ethical Hacking Bootcamp",p:"Packt",c:3,cat:"spec"},
    {id:17,t:"Selenium Python Automation Testing",p:"Packt",c:3,cat:"spec"},
    {id:18,t:"Advanced Python Scripting for Cybersecurity",p:"Infosec",c:3,cat:"spec"},
    {id:19,t:"Generative AI: Prompt Engineering Basics",p:"IBM",c:1,cat:"ai"},
    {id:20,t:"Generative AI: Introduction and Applications",p:"IBM",c:1,cat:"ai"},
    {id:21,t:"Generative AI: Boost Your Cybersecurity Career",p:"IBM",c:1,cat:"ai"},
    {id:22,t:"Applied ChatGPT for Cybersecurity",p:"Infosec",c:1,cat:"ai"},
    {id:23,t:"Red Teaming LLM Applications",p:"DeepLearning.AI",c:1,cat:"ai"},
    {id:24,t:"Optimizing Workflow with GitHub Copilot",p:"Microsoft",c:1,cat:"ai"},
    {id:25,t:"Secure Full Stack MEAN Developer",p:"EC-Council",c:1,cat:"dev"},
    {id:26,t:"Security Operations Center (SOC)",p:"EC-Council",c:1,cat:"sec"},
    {id:27,t:"Penetration Testing, Threat Hunting & Cryptography",p:"IBM",c:1,cat:"sec"},
    {id:28,t:"The Complete Pentesting & Privilege Escalation",p:"Packt",c:1,cat:"sec"},
    {id:29,t:"Web Hacker's Toolbox",p:"Packt",c:1,cat:"sec"},
    {id:30,t:"Intermediate Ethical Hacking Hands-on",p:"Packt",c:1,cat:"sec"},
    {id:31,t:"Nmap for Penetration Testing",p:"Packt",c:1,cat:"sec"},
    {id:32,t:"Introduction to AWS Pentesting",p:"Packt",c:1,cat:"sec"},
    {id:33,t:"Offensive Hacking Unfolded",p:"Packt",c:1,cat:"sec"},
    {id:34,t:"Pentesting Fundamentals for Beginners",p:"Packt",c:1,cat:"sec"},
    {id:35,t:"Security & Risk Management",p:"Packt",c:1,cat:"sec"},
    {id:36,t:"Web App Security Testing with OWASP ZAP",p:"Coursera",c:1,cat:"sec"},
    {id:37,t:"Introduction to Computer Security",p:"University of London",c:1,cat:"sec"},
    {id:38,t:"Metasploit for Beginners",p:"Coursera",c:1,cat:"sec"},
    {id:39,t:"Cybersecurity for Managers",p:"Campus BBVA",c:1,cat:"sec"},
    {id:40,t:"Cybersecurity in Healthcare",p:"Erasmus University Rotterdam",c:1,cat:"sec"},
    {id:41,t:"Cybersecurity for Everyone",p:"University of Maryland",c:1,cat:"sec"},
    {id:42,t:"International Cyber Conflicts",p:"SUNY",c:1,cat:"sec"},
    {id:43,t:"Security & Ethical Hacking: Attacking the Network",p:"UC Boulder",c:1,cat:"sec"},
    {id:44,t:"Introduction to Cybersecurity Tools & Cyberattacks",p:"IBM",c:1,cat:"sec"},
    {id:45,t:"Introduction to Cybersecurity Fundamentals",p:"Coursera",c:1,cat:"sec"},
    {id:46,t:"Ethical Hacking Fundamentals",p:"LearnKartS",c:1,cat:"sec"},
    {id:47,t:"Advanced Ethical Hacking & Cybersecurity",p:"LearnKartS",c:1,cat:"sec"},
    {id:48,t:"System & Network Security Essentials",p:"LearnKartS",c:1,cat:"sec"},
    {id:49,t:"Ethical Hacking Practice Project",p:"LearnKartS",c:1,cat:"sec"},
    {id:50,t:"Postman Tutorial: API Testing",p:"Packt",c:1,cat:"dev"},
    {id:51,t:"Start Your API Testing with Postman",p:"Coursera",c:1,cat:"dev"},
    {id:52,t:"Computer Hardware and Software",p:"UC Irvine",c:1,cat:"other"},
    {id:53,t:"Developing a Leadership Framework",p:"Kennesaw State University",c:1,cat:"other"},
    {id:54,t:"Introduction to Psychology",p:"Yale University",c:1,cat:"other"},
    {id:55,t:"Astrobiology & Extraterrestrial Life",p:"University of Edinburgh",c:1,cat:"other"}
  ],
  projects: [
    {id:1,title:"Neural Sentinel",desc:"AI-powered intrusion detection system using deep learning for zero-day attack identification in real-time.",tech:["Python","TensorFlow","FastAPI","Docker"],icon:"fa-brain",link:"",github:""},
    {id:2,title:"VibeCoder Engine",desc:"AI-augmented IDE that generates, reviews & optimizes code using fine-tuned LLMs and prompt engineering.",tech:["React","Node.js","OpenAI","LangChain"],icon:"fa-wand-magic-sparkles",link:"",github:""},
    {id:3,title:"PhantomScan",desc:"Automated vulnerability scanner & pentesting framework with intelligent exploit suggestion engine.",tech:["Python","Nmap","Metasploit","Docker"],icon:"fa-ghost",link:"",github:""},
    {id:4,title:"SenseiDojo",desc:"Interactive platform for AI development, prompt engineering & cybersecurity training.",tech:["Next.js","Python","WebSocket","PostgreSQL"],icon:"fa-torii-gate",link:"",github:""},
    {id:5,title:"CryptoVault",desc:"End-to-end encrypted communication with zero-knowledge architecture. Built with a pentester's paranoia.",tech:["TypeScript","Rust","WebCrypto","React"],icon:"fa-vault",link:"",github:""},
    {id:6,title:"AIShield",desc:"Red teaming toolkit for LLM applications — testing AI for prompt injection & adversarial attacks.",tech:["Python","LangChain","OpenAI","FastAPI"],icon:"fa-shield-halved",link:"",github:""}
  ],
  testimonials: [
    {id:1,name:"Sample Student",initials:"SS",course:"AI-Augmented Dev Bootcamp",rating:5,text:"Adhi's teaching is incredible. Complex AI & prompt engineering made digestible. The hands-on projects were game-changers.",linkedin:"https://linkedin.com/in/"},
    {id:2,name:"Another Student",initials:"AS",course:"Cybersecurity Fundamentals",rating:5,text:"Learning from an actual ethical hacker gives a totally different perspective on writing secure code. Best investment ever.",linkedin:"https://linkedin.com/in/"},
    {id:3,name:"Third Student",initials:"TS",course:"Prompt Engineering Masterclass",rating:5,text:"From basic prompts to production AI systems with LangChain — this course changed my entire career trajectory.",linkedin:"https://linkedin.com/in/"}
  ],
  settings: { adminPass: "adhi2024" }
};

function getData(){const r=localStorage.getItem(DATA_KEY);if(!r){localStorage.setItem(DATA_KEY,JSON.stringify(DEFAULT_DATA));return JSON.parse(JSON.stringify(DEFAULT_DATA));}try{return JSON.parse(r)}catch(e){return JSON.parse(JSON.stringify(DEFAULT_DATA))}}
function saveData(d){localStorage.setItem(DATA_KEY,JSON.stringify(d))}
function resetData(){localStorage.setItem(DATA_KEY,JSON.stringify(DEFAULT_DATA));return JSON.parse(JSON.stringify(DEFAULT_DATA))}
